### PR TITLE
keis/modifier-key-events-rebased

### PR DESCRIPTION
**Pull request by mathstuf**
- Fix mouse buttons support
- Mask out ignored modifiers (Mod2)
- Add events for double and triple clicks

### CODE REVIEW

**Comment by keis** [comment]
bct already pulled this branch into experimental, after rebasing it again (I think) and with some further tweaks.
these patches does not apply cleanly to experimental.

**Comment by mathstuf** [comment]
I've now merged experimental into the branch and resolved conflicts there.

**Comment by keis** [comment]
I'm going to try to cherry pick the mouse stuff. But I'm not 100% sure on what the semantics for when to forward and when to send events should be (why not always send events?).

**Comment by mathstuf** [comment]
If uzbl takes all the mouse events, then you miss being able to actually get a click into webkit itself. So users would be unable to click forms, buttons, get a context menu, etc. without having some script to pass it back into webkit itself.

**Comment by mathstuf** [comment]
I wonder if we actually should eat all mouse events. We would need a plugin to handle existing functionality (as well as a new event to tell the position of the click, repetition count, and button number). To actually interact with the page, the user would need to be in `[Ins]` mode.

**Comment by keis** [comment]
Iirc, we can both send event and propagate the click to webkit.

Sent from my portable toaster

On Apr 23, 2011 5:22 PM, "mathstuf" <
reply@reply.github.com>
wrote:

I wonder if we actually should eat all mouse events. We would need a plugin
to handle existing functionality (as well as a new event to tell the
position of the click, repetition count, and button number). To actually
interact with the page, the user would need to be in `[Ins]` mode.

**Comment by mathstuf** [comment]
On Sat, Apr 23, 2011 at 09:07:14 -0700, keis wrote:

> Iirc, we can both send event and propagate the click to webkit.

True, but I don't think we should send events which are being otherwise
handled internally. I think doing mouse clicks only in `[Ins]` mode
would be a solution to this (with the default scripts handling these as
expected).

A different event for mouse clicks makes sense in any case because
information such as location would be useful.

**Comment by mathstuf** [comment]
Hmm, I don't think this is useful anymore :) .

**Pull request closed without merging**
